[env:custom_f411ce]
platform = ststm32
board = genericSTM32F411CE
framework = arduino

upload_protocol = stlink

lib_deps =
    etlcpp/Embedded Template Library

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++20
    -DHSE_VALUE=16000000U