[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino

build_unflags = 
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++20
    -DUSBCON
    -DUSBD_USE_CDC
    -DHSE_VALUE=16000000U